SCRUM-95: Users service; create & read
TPII-PadelPals/users-service pull request #1
Opened 2024-12-11 20:46 UTC by dima1997

Create Users services with:
- User table
  - Create and Read
  - Primary key: autoincremental ID
  - Unique: public_id, email
  - Extra index on id + public_id

2024-12-14 14:07 UTC, dima1997 commented
PR "SCRUM-95: Users services; create & read" is ready to be reviewed

2024-12-14 14:09 UTC, dima1997 commented
After "Approval", "Squash and merge" with the following information:
* Title: 
````
SCRUM-95: Users service; create & read
````
* Description: 
```
Create Users services with:
* User table
  * Create and Read
  * Primary key: autoincremental ID
  * Unique: public_id, email
  * Extra index on id + public_id
```

2024-12-16 16:00 UTC, amaruDuran commented on app/api/routes/users.py
> +    return UsersPublic(data=users, count=count)
Buenas! Me hace un poco de ruido este endpoint.

Que utilidad tendría en el bot o en el caso de los dueños?

No veo una historia a alto nivel relacionada con esta funcionalidad, simplemente por eso

2024-12-16 16:11 UTC, amaruDuran commented on app/models/user.py
> +    phone: str = Field(unique=True)
Se permiten crear usuarios con:
- nombre vacío
- emails sin "@"
- telefono con valores no numéricos

Respecto al nombre, sumaría una condición de que al menos tenga N caracteres.
Para validar el teléfono e email, si te parece creamos 2 features de validación externos a este PR

```suggestion
class UserBase(SQLModel):
    name: str = Field(min_length=1, max_length=255)
```

2024-12-16 16:40 UTC, amaruDuran commented on app/repository/users_repository.py
> +            raise NotUniqueException(item=attr.capitalize())
Me parecería más legible si está escrito:
- evitaría los doble negado (not None) que a veces confunde

```suggestion
        user_attr = getattr(User, attr)
        statement = select(user_attr).where(user_attr == value)
        attr_exist = (await self.session.exec(statement)).first()
        if attr_exist:
            raise NotUniqueException(item=attr.capitalize())
```

2024-12-16 16:56 UTC, amaruDuran commented on app/tests/api/routes/test_users.py
> +        assert user["public_id"] == user_data["public_id"]
Muy bueno este tipo de test,
habrá forma de comparar (hacer assert) también los atributos de los usuarios generados?

Más que nada para saber viendo el test, que parámetros son públicos y que devuelve cuando le pego al endpoint, así como lo hacés en `test_read_user_not_found`

2024-12-16 17:02 UTC, amaruDuran commented on app/tests/repository/test_users_repository.py
> +    assert len(str(user.public_id)) == len(str(uuid.uuid4()))
```suggestion
```

2024-12-16 17:15 UTC, amaruDuran commented on app/tests/repository/test_users_repository.py
> +        assert True
Para testear la excepción creo que podés hacer algo del estilo:

```suggestion
    with pytest.raises(NotUniqueException) as e:
        await repo.create_user(user_create)

    assert str(e.value) == "Email already exists"
```

2024-12-16 17:17 UTC, amaruDuran commented on app/tests/repository/test_users_repository.py
> +        assert True
Agregaría un test muy similar para tomar la excepción de que un teléfono no sea único.

2024-12-16 17:19 UTC, amaruDuran commented on app/tests/repository/test_users_repository.py
> +async def test_create_user_not_unique(session: AsyncSession) -> None:
```suggestion
async def test_create_user_with_already_exists_email_returns_exception(session: AsyncSession) -> None:
```

2024-12-16 17:22 UTC, amaruDuran requested changes
El PR en general lo veo bien, con manejo de varios casos de uso y errores.

Dejé un par de comentarios y cositas a corregir junto con algunos debates pero en general bien.

Cualquier duda comentame en el PR que lo vemos

2024-12-16 18:43 UTC, dima1997 commented on app/api/routes/users.py
> +    return UsersPublic(data=users, count=count)
La US en cuestión solicita las operaciones de Create & Read, que en el service-template estan implementados a nivel de los endpoints y de la base de datos. Por eso este endpoint.

En terminos de utilidad, podría servir para los administradores de la aplicación.

Propongo mantener la funcionalidad en el código.

2024-12-16 18:54 UTC, dima1997 commented on app/models/user.py
> +    phone: str = Field(unique=True)
Creo USs [SCRUM-116](https://tpii-padel-pals.atlassian.net/browse/SCRUM-116) y [SCRUM-117](https://tpii-padel-pals.atlassian.net/browse/SCRUM-117) para la validación de la dirección de email y los telefonos.

Procedo a restringir la longitud de los nombres.

2024-12-16 20:07 UTC, dima1997 commented on app/repository/users_repository.py
> +            raise NotUniqueException(item=attr.capitalize())
Procedo a realizar la corrección solicitada

2024-12-16 20:11 UTC, dima1997 commented on app/tests/api/routes/test_users.py
> +        assert user["public_id"] == user_data["public_id"]
Dado que èl test `test_read_user` ya mostraba los atributos publicos, no me parecio necesario volver a testearlos.

Por esta ocasión, procedo a agregar los atributos faltantes a los tests con for loop

2024-12-16 20:14 UTC, dima1997 commented on app/tests/repository/test_users_repository.py
> +    assert len(str(user.public_id)) == len(str(uuid.uuid4()))
Necesito validar que el atributo es generado, que existe.

Propongo dejarlo como esta ahora.

2024-12-16 20:34 UTC, dima1997 commented on app/tests/repository/test_users_repository.py
> +        assert True
Procedo a realizar las correcciones

2024-12-16 20:34 UTC, dima1997 commented on app/tests/repository/test_users_repository.py
> +async def test_create_user_not_unique(session: AsyncSession) -> None:
Procedo a realizar las correcciones

2024-12-16 21:54 UTC, amaruDuran commented on app/api/routes/users.py
> +    return UsersPublic(data=users, count=count)
Dale, lo mantenemos, de todas formas si se implementa el api gateway el será el encargado de mostrar y pegarle a las apis que tengamos. Así que si no llegamos a usar este endpoint no molesta por el momento

2024-12-16 22:32 UTC, amaruDuran commented on app/utilities/exceptions.py
> +        super().__init__(status_code=status.HTTP_409_CONFLICT, detail=detail)
Que opinás sobre segregar los errores, y que tengas por un lado, errores para el repositorio y por otro errores para la api en si. En este caso este sería un error para la api.


Esto para poder hacer un mejor seguimiento y desde el código se pueda ver el flujo de errores que puede tener la api haciendo un try-except desde la api de los errores que puede tener el repositorio que se llame

Si querés para ello mirate el pr de business y mira como lo plantee:
![image](https://github.com/user-attachments/assets/264ab3ed-0e6f-4729-add7-db5e798d0a4d)

Quedará igual para otro PR si te parece

2024-12-16 22:33 UTC, amaruDuran approved these changes

2024-12-16 22:34 UTC, amaruDuran commented on app/utilities/exceptions.py
> +        super().__init__(status_code=status.HTTP_409_CONFLICT, detail=detail)
Por el resto, todo joya

2024-12-16 22:41 UTC, merged