SCRUM-104: Migrate Google registration
TPII-PadelPals/users-service pull request #3
Opened 2024-12-20 18:15 UTC by dima1997

- Add Google registration based on Backend repository code 
- Add read_users based on telegram_id

2024-12-20 22:31 UTC, dima1997 commented
El testeo manual end-to-end desde la aplicación de telegram depende de la US: [SCRUM-96](https://tpii-padel-pals.atlassian.net/browse/SCRUM-96)

[SCRUM-96]: https://tpii-padel-pals.atlassian.net/browse/SCRUM-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-20 22:31 UTC, dima1997 commented
La remoción y adaptación del registro con google del repositorio backend para utilizar esta migración se realizará en la siguiente US [SCRUM-122](https://tpii-padel-pals.atlassian.net/browse/SCRUM-122)

[SCRUM-122]: https://tpii-padel-pals.atlassian.net/browse/SCRUM-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-21 17:40 UTC, tdelpup requested changes
### Debatir en un futuro

- Código de Auth lo dejamos en el mismo servicio que el de usuario?
- Cuando se agregue otro método de registro/login, habría que cambiar la ruta a `/auth/xxx`( hoy se encuentra como `/google/auth` )

### Review Summary

- Cambiar nombres de routers para ser más explícitos
- Agregar `chat_id` a parámetro para validación automática (tener en cuenta reemplazar `chat_id` por `telegram_id`)
- Separar la lógica del endpoint en un service
- Reemplazar los responses de los endpoints (ej: USER_RESPONSES)

2024-12-21 17:40 UTC, tdelpup commented on .env.example
> +TELEGRAM_BOT_USERNAME=padelpals-franco-test
```suggestion
TELEGRAM_BOT_USERNAME=
```
Creo que esta variable de entorno conviene dejarla vacía para que los que prueben se den cuenta que lo tienen que llenar en la validación de las .env
Muchas veces se saca el `.example` del `.env.example` y se fijan solo las faltantes

2024-12-21 17:40 UTC, tdelpup commented on app/api/routes/google.py
> +    """
Por que se separa la lógica del endpoint en una función separada?
Si la idea es para que la logica no quede en la declaración del endpoint, convendría crear un GoogleService y mandar esas funciones a métodos de este

2024-12-21 17:40 UTC, tdelpup commented on app/api/routes/users.py
>      return user
Lo mismo que en el comentario de google, queda raro que en la declaración de los endpoints hayan funciones `ìnner`que solo encapsulan la lógica del endpoint. Se puede dejar esto como metodos de un UserService

2024-12-21 17:40 UTC, tdelpup commented on app/core/config.py
> +
Esta bueno esto

2024-12-21 17:40 UTC, tdelpup commented on app/api/main.py
> +)
Les cambiaría el nombre. Si bien se puede intuir esta raro el `open` y el `token` también, por que lo que se le pasa es una key. Seguramente cuando hagamos el agregado con JWT (token), se nos van a mezclar

```suggestion
router_without_api_key = APIRouter()
router_without_api_key.include_router(google.router, prefix="/google", tags=["google"])

router_with_api_key = APIRouter(
    dependencies=[Depends(get_token_header)],
)
```

2024-12-21 17:40 UTC, tdelpup commented on app/models/user.py
El id de telegram no iba en el jugador? o cuando se haga la tarea [SCRUM-122](https://tpii-padel-pals.atlassian.net/browse/SCRUM-122) esto va a ser modificado?

2024-12-21 17:40 UTC, tdelpup commented on docker-compose.override.yml
>      restart: "no"
Cambiar a nombre al estilo `users-service`, para que al hacer `docker ps` o `docker compose ls` se entienda que servicio esta corriendo

2024-12-21 17:40 UTC, tdelpup commented on docker-compose.yml
>      build: .
Cambiar a nombre al estilo `users-service`, para que al hacer `docker ps` o `docker compose ls` se entienda que servicio esta corriendo

2024-12-21 17:40 UTC, tdelpup commented on app/api/routes/users.py
>  )
No se en que momento se agrego esto `responses={**USER_RESPONSES}`, pero esta mal.
Indicar ahí los tipos de respuesta, sirve para la doc de swagger/openapi. Al ponerle a todos los endpoints el `responses={**USER_RESPONSES}`, todos tienen los mismos tipos de respuesta, lo cual esta mal.

Para poner de ejemplo: [Ver en entorno local](http://127.0.0.1:8000/docs#/users/users-read_users)
Endpoint: `/api/v1/users/`
Intención: Devolver un listado de usuarios
Posibles respuestas:
- 200
- 404: user not found
- 409: Email or phone already exists
- 422: validation error

Lo cual no tiene sentido por que parte de esas respuestas son de los otros métodos. Hay que separar las respuestas e incluirlas individualmente.

2024-12-21 17:40 UTC, tdelpup commented on app/api/routes/google.py
> +async def google_auth(request: Request) -> Any:
Agregar el `chat_id` como parámetro para que el endpoint ya valide que existe. Si no existe va a devolver un 422 validation error.
No es necesario obtenerlo como `chat_id = request.query_params.get("chat_id")`
Además se agrega automáticamente como parámetro en el swagger/openapi 
Se que antes no estaba asi, pero es la manera correcta de hacerlo :)
```suggestion
async def google_auth(request: Request, chat_id: str) -> Any:
```

2024-12-21 17:40 UTC, tdelpup commented on app/api/routes/google.py
Se podrían reemplazar todos los `chat_id` por `telegram_id` para que quede consistente con el modelo

2024-12-22 04:32 UTC, dima1997 commented on app/api/routes/google.py
> +    """
Es para poder inyectar el oauth y, entonces, inyectar un oauth_mock para poder testear el endpoint sin tener que interactuar verdaderamente con Google, haciendo el test mas rapido y menos dependiente de factores externos.

Procedo a crear el GoogleService para que quede más prolijo

2024-12-22 04:33 UTC, dima1997 commented on app/api/routes/users.py
>      return user
En este caso, es para evitar repetir codigo entre los paths de user y google.

Procedo a crear la clase UserService

2024-12-22 04:38 UTC, dima1997 commented on app/api/routes/google.py
Si, pero habrá que cambiar eso tambien del lado del bot.

Procedo a realizar el cambio del lado del users-service

2024-12-22 04:38 UTC, dima1997 commented on app/api/routes/google.py
> +async def google_auth(request: Request) -> Any:
Ok :)

2024-12-22 04:38 UTC, dima1997 commented on app/api/routes/users.py
>  )
Procedo a realizar los cambios solicitados

2024-12-22 04:44 UTC, dima1997 commented on app/api/main.py
> +)
Procedo a realizar las moficaciones solcitadas

2024-12-22 04:57 UTC, dima1997 commented on docker-compose.override.yml
>      restart: "no"
Originalmente, lo habia nombrado users-service, pero cuando levantaba el servicio quedaba como como users-service-service, por eso lo habia nombrado app para que quedease app-service.

Procedo a realizar las moficaciones solicitadas

2024-12-22 04:58 UTC, dima1997 commented on docker-compose.yml
>      build: .
Idem.

Procedo a realizar las modificaciones solicitadas

2024-12-22 06:35 UTC, dima1997 commented
> ### Debatir en un futuro
> * Código de Auth lo dejamos en el mismo servicio que el de usuario?
> * Cuando se agregue otro método de registro/login, habría que cambiar la ruta a `/auth/xxx`( hoy se encuentra como `/google/auth` )

Creo nueva US en el backlog para discutir al respecto: [SCRUM-123](https://tpii-padel-pals.atlassian.net/browse/SCRUM-123)

> ### Review Summary
> * Cambiar nombres de routers para ser más explícitos
> * Agregar `chat_id` a parámetro para validación automática (tener en cuenta reemplazar `chat_id` por `telegram_id`)
> * Separar la lógica del endpoint en un service
> * Reemplazar los responses de los endpoints (ej: USER_RESPONSES)

Correcciones realizadas.

[SCRUM-123]: https://tpii-padel-pals.atlassian.net/browse/SCRUM-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-12-22 14:02 UTC, tdelpup requested changes

2024-12-22 14:02 UTC, tdelpup commented on app/tests/services/test_google_service.py
> +    print(f"{expected_html = }")
Eliminar prints

2024-12-22 14:02 UTC, tdelpup commented on app/services/google_service.py
> +        self.users_service = users_service
El UsersService debería ser inicializado dentro del __init__ , no pasado como parámetro default si nunca va a pasarse otra cosa ( Si es por el mock, se puede mockear sin pasar como parámetro )

2024-12-22 23:54 UTC, tdelpup approved these changes

2024-12-22 23:56 UTC, merged